# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: ibmcase
  name: wfd-dessert
  tag: spring
  pullPolicy: Always
  containerPort: 8083
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
service:
  name: Node
  type: ClusterIP
  servicePort: 8083
