spring:
  application:
    name: dessert-service
#  cloud:
#    client:
#      hostname: localhost

server:
  port: 8083

eureka:
  instance:
#    hostname: localhost
    preferIpAddress: true
  client:
    serviceUrl:
       defaultZone: http://localhost:8761/eureka/

wfd:
  dessert:
    order: 3
    type: dessert
    menu:
      - Chocolate Cake
      - Banoffee
      - Ice Cream
