apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: wfddessert
data:
  application.yaml: |+
    spring:
      sleuth:
        sampler:
          percentage: 1.0
      zipkin:
        baseUrl: http://{{ .Values.zipkin.service }}:{{ .Values.zipkin.port }}

    server:
      port: {{ .Values.image.containerPort }}

    eureka:
      client:
        serviceUrl:
           defaultZone: http://{{ .Values.eureka.service }}:{{ .Values.eureka.port }}/eureka/
      instance:
        preferIpAddress: {{ .Values.eureka.preferIpAddress }}

    wfd:
      dessert:
        order: 3
        type: dessert
        menu:
          - Chocolate Cake
          - Banoffee
          - Ice Cream

  bootstrap.yaml: |+
    spring:
      application:
        name: wfddessert-service
